version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: kmone-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: kmone
    ports:
      - "5432:5432"
    volumes:
      - kmone_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  kmone_data:
