service: kmone-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: staging
  httpApi:
    payload: "2.0"
    cors: true
    binaryMediaTypes:
      - application/octet-stream
      - image/*
  environment:
    NODE_ENV: production
    DATABASE_URL: postgresql://neondb_owner:npg_Tpc2Qa5YBumJ@ep-bold-wind-achnwl93-pooler.sa-east-1.aws.neon.tech/kmone?sslmode=require&channel_binding=require

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

package:
  patterns:
    - dist/**
    - node_modules/**
    - package.json
    - "!**/*.map"
    - "!src/**"
