service: kmone-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  stage: ${env:STAGE, 'staging'}
  httpApi:
    cors: true
  environment:
    NODE_ENV: "production"
    DATABASE_URL: ${env:DATABASE_URL}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

package:
  patterns:
    - dist/**
    - node_modules/**
    - "!**/*.map"
    - "!src/**"
