service: kmone-backend
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  stage: staging
  httpApi:
    payload: "2.0"
    cors:
      allowedOrigins:
        - "*" # libera para qualquer origem
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowedHeaders:
        - Content-Type
        - Authorization
      maxAge: 86400

  environment:
    NODE_ENV: "production"
    DATABASE_URL: ${env:DATABASE_URL, 'dummy'}

functions:
  api:
    handler: dist/handler.handler
    events:
      - httpApi: "*"

package:
  patterns:
    - dist/**
    - node_modules/**
    - package.json
    - "!**/*.map"
    - "!src/**"
