name: Backend Deploy (Lambda)

on:
  push:
    branches: [develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy-lambda.yml"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      AWS_REGION: ${{ vars.AWS_REGION }} # <- variável, não secret
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # <- secret
      STAGE: staging
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy with Serverless
        run: npx serverless deploy
