name: Backend Deploy (Lambda)

on:
  push:
    branches: [develop]
    paths:
      - "backend/**"
      - ".github/workflows/backend-deploy-lambda.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # OIDC para assumir Role na AWS
      contents: read
    defaults:
      run:
        working-directory: backend
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }} # Neon/Supabase
      STAGE: staging
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy with Serverless
        run: npx serverless deploy
